### PR TITLE
Deploy to Heroku

### PR DESCRIPTION
**Pull request by eliottha**
Done #3

### CODE REVIEW

**Comment by RishabhTayal** [comment]
Getting error when deploying.

screenshot 2018-01-01 12 11 49

**Comment by eliottha** [comment]
- - Yes because url is set to https://github.com/RishabhTayal/itc-api/ but therefore it must be migrated...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
Got it.

**Comment by eliottha** [comment]
If you change url to https://github.com/Eliottiosdevs/itc-api/ it works

**Comment by eliottha** [comment]
in app.json

**Comment by RishabhTayal** [comment]
Merged!

**Comment by eliottha** [comment]
Thanks! Does it work?

**Pull request merged**
