### PR TITLE
app_status endpoint to return current version status

### PR DESCRIPTION
**Pull request by vlondon**

### CODE REVIEW

**Comment by RishabhTayal** [comment]
@vlondon What exactly does this pr do? Does this fix something or implement something new? Please provide some details in the description.

**Comment by eliottha** [comment]
@RishabhTayal added The app status, like in my meta pr, eg. Waiting for review.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eliottha** [comment]
The only difference is that @vlondon uses edit_version and I’m looking go get live first and if empty the edit_version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
Closing this

**Pull request closed without merging**
